Refactor build tools

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -761,7 +761,7 @@ findComponents() {
  
             if [ ! -f "${BLD_TOP}/build/components/${name}" ] ; then
                 echo "Missing component file: build/components/$name"
-                continue
+                exit 255
             fi
 
             eval BLD_UNIX_LIKE=\$BLD_${kind}_UNIX              
@@ -998,7 +998,9 @@ configureComponent() {
     value=${path}
     [ "$value" = "" ] && value=1
     [ "$iflags" = "-I/usr/include" ] && iflags=
-
+    if [ "$libpaths" = "/usr/lib" -o "$libpaths" = "/lib" ] ; then
+        libpaths=
+    fi
     eval CFG_${kind}_${upper}=\"${value}\"
     eval CFG_${kind}_${upper}_BUILTIN=\"$builtin\"
     eval CFG_${kind}_${upper}_CFLAGS=\"$cflags\"
@@ -1012,10 +1014,12 @@ configureComponent() {
     eval CFG_${kind}_${upper}_LIBPATHS=\"$libpaths\"
     eval CFG_${kind}_${upper}_MANDATORY=\"$mandatory\"
     eval CFG_${kind}_${upper}_OPTIONAL_DEPENDENCIES=\"$optional\"
-    eval CFG_${kind}_${upper}_WITHLIBS=\"$withlibs\"
-    eval CFG_${kind}_${upper}_WITHPATHS=\"$withpaths\"
+    if [ "$builtin" = 1 ] ; then
+        eval CFG_${kind}_${upper}_WITHLIBS=\"$withlibs\"
+        eval CFG_${kind}_${upper}_WITHPATHS=\"$withpaths\"
+    fi
     eval ${kind}_COMPONENTS=\"\$${kind}_COMPONENTS ${name}\"
-    tag=${tag:-system}
+    tag=${tag:-imported}
     [ $quiet = 0 -a $verbose = 0 -a $kind = HOST ] && echo "$tag"
 }
 
@@ -1232,7 +1236,8 @@ without() {
     lowerName=`lower ${name}`
 
     if [ ! -f build/components/${lowerName} ] ; then
-        echo -e "\nUnknown component \"${name}\". Ignoring and continuing ...\n"
+        echo -e "\nCan't locate component \"${name}\".\n"
+        exit 255
     fi
     components=" ${BLD_COMPONENTS} "
     if [ "${components/ $lowerName /}" = "$components" ] ; then
@@ -1240,6 +1245,8 @@ without() {
     fi
     BLD_COMPONENTS="${components/ $lowerName / }"
     eval "CFG_WITHOUT_${upperName}"=1
+    eval "CFG_HOST_${upperName}_WITH"=0
+    eval "CFG_BUILD_${upperName}_WITH"=0
     eval "BLD_FEATURE_${upperName}"=0
 }
 
@@ -1452,6 +1459,8 @@ createConfigFooter()
     then
         cat >>$FILE <<!EOF_CONFIG_FOOTER_MAKE
 # End of Makefile definitions
+
+
 else
 #else /* !IGNORE_IN_C_CODE */
 
@@ -1635,6 +1644,7 @@ BLD_IMPORTS="${BLD_IMPORTS}"
 
 !EOF_STANDARD_FEATURES
 
+    #   MOB - would be better if this emitted to stdout instead of to $FILE
     createFeatureConfig $FILE
 
     #
@@ -1681,6 +1691,8 @@ BLD_IMPORTS="${BLD_IMPORTS}"
         [ "$FILE" = "$CONFIG_H" ] && echo -e 'endif\n' >>$FILE
         [ "$FILE" = "$CONFIG_SRC" ] && echo -e ' _#endif' >>$FILE
     fi
+    echo '' >>$FILE
+
     if [ "$FILE" = "$CONFIG_H" ] ; then
         echo 'EXPORT_OBJECTS ?= 1' >>$FILE
         echo 'ifeq ($(EXPORT_OBJECTS),0)' >>$FILE
@@ -1767,9 +1779,12 @@ createCrossConfig()
     eval v=\$BLD_${kind}_BIN_DIR ; echo -e "${t}BLD_BIN_DIR=\"${v}\""
     eval v=\$BLD_${kind}_OBJ_DIR ; echo -e "${t}BLD_OBJ_DIR=\"${v}\""
     eval v=\$BLD_${kind}_MOD_DIR ; echo -e "${t}BLD_MOD_DIR=\"${v}\""
-    eval v=\$BLD_${kind}_JEM_DIR ; echo -e "${t}BLD_JEM_DIR=\"${v}\""
     eval v=\$BLD_${kind}_LIB_DIR ; echo -e "${t}BLD_LIB_DIR=\"${v}\""
     eval v=\$BLD_${kind}_INC_DIR ; echo -e "${t}BLD_INC_DIR=\"${v}\""
+
+    # if [ "$BLD_PRODUCT" = "ejs" -o "$CFG_HOST_EJS_WITH" = 1 ] ; then
+    #     eval v=\$BLD_${kind}_JEM_DIR ; echo -e "${t}BLD_JEM_DIR=\"${v}\""
+    # fi
 
     echo
     eval v=\${BLD_OUT_DIR} ; v=`eval canonPath "${v}"` ; echo -e "${t}BLD_ABS_OUT_DIR=\"${v}\""
@@ -1778,9 +1793,9 @@ createCrossConfig()
     eval v=\${BLD_${kind}_OBJ_DIR} ; v=`eval canonPath "${v}"` ; echo -e "${t}BLD_ABS_OBJ_DIR=\"${v}\"" ; mkdir -p "${v}"
     eval v=\${BLD_${kind}_MOD_DIR} ; v=`eval canonPath "${v}"` ; echo -e "${t}BLD_ABS_MOD_DIR=\"${v}\"" ; mkdir -p "${v}"
 
-    if [ "$CFG_HOST_EJS_WITH" = 1 ] ; then
-        eval v=\${BLD_${kind}_JEM_DIR} ; v=`eval canonPath "${v}"` ; echo -e "${t}BLD_ABS_JEM_DIR=\"${v}\"" ; mkdir -p "${v}"
-    fi
+    # if [ "$BLD_PRODUCT" = "ejs" -o "$CFG_HOST_EJS_WITH" = 1 ] ; then
+    #     eval v=\${BLD_${kind}_JEM_DIR} ; v=`eval canonPath "${v}"` ; echo -e "${t}BLD_ABS_JEM_DIR=\"${v}\"" ; mkdir -p "${v}"
+    # fi
     eval v=\${BLD_${kind}_INC_DIR} ; v=`eval canonPath "${v}"` ; echo -e "${t}BLD_ABS_INC_DIR=\"${v}\"" ; mkdir -p "${v}"
 
     if [ $name != $CONFIG_SRC ] ; then
@@ -1822,7 +1837,6 @@ createCrossConfig()
         echo -e "\n${t}#\n${t}#\tBuild Tools Features\n${t}#"
         echo -e "${t}BLD_FEATURE_ROMFS=0"
     fi
-
     emitComponents $kind
 }
 
@@ -1878,6 +1892,7 @@ emitComponents() {
         v=${v/WITHOUT/FEATURE}
         echo -e "${t}${v#_}=0"
     done
+    emitExtraComponents $kind
 }
 
 
@@ -2085,12 +2100,18 @@ Environment Variables:
   LDFLAGS                  Linker flags. For example: use -L<dir> to specify
                            where to find libraries in non-standard directories.
 
-Variables for native compilation of tools needed by the build process.
+  Variables for native compilation of tools needed by the build process:
+
   BUILD_CC                 C/C++ compiler to use for native /local compilation
                            and linking on the build system.
   BUILD_LD                 Linker to use for native /local linking on the
                            build system.
   BUILD_MT                 Windows manifest command.
+
+  Some components also listen for environment variables to set IFLAGS, LIBS and
+  LIBPATHS. For example:  
+
+    PHP_IFLAGS="-I/php" PHP_LIBS=libxml ./configure
 
 Installation Directory Options:
   When doing a "make install" the --prefix and --binDir are used. The other
