Fix import paths on windows

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -596,7 +596,10 @@ relativePath() {
 
     home="$PWD"
 
-    dir="$1"
+    #
+    #   Expand ${BLD_TOP}
+    #
+    eval dir="$1"
 
     if [ "BLD_HOST_OS" = "WIN" -o "$BLD_HOST_OS" = "WINCE" ] ; then
         dir=`canonPath "$dir" | tr '[A-Z]' '[a-z]'`
@@ -843,7 +846,7 @@ warnComponent() {
 #
 configureComponent() {
     local cflags dflags dependencies kind iflags imports ldflags libpaths libs name upperDep new present needed
-    local path withlibs withpaths upper priorMandatory priorPath emitter disable optional v tag builtin
+    local path withlibs withpaths upper priorMandatory priorPath emitter disable optional v tag builtin f newImports
 
     kind=$KIND
     builtin=0
@@ -988,6 +991,13 @@ configureComponent() {
         done
         iflags="$new"
     fi
+    newImports=
+    for f in $imports ; do
+        f=`relativePath "${f}"`
+        newImports="${f} $newImports"
+    done
+    imports="$newImports"
+
     if [ "$imports" != "" ] ; then
         BLD_IMPORTS="$imports $BLD_IMPORTS"
     fi
@@ -1969,6 +1979,7 @@ showBuildConfig() {
             echo -e "  #   ${p}   ${dir}"
         fi
     done
+    echo -e "  #"
     echo
 }
 
@@ -2025,10 +2036,13 @@ doImports() {
         # Windows puts relative paths in BLD_IMPORTS using ${BLD_TOP}
         eval f="${f}"
         ext=".${f##*.}"
-        if [ "${ext}" = ".h" ] ; then
+        if [ ! -f "${f}" ] ; then
+            echo "Can't find ${f} to import"
+            exit 255
+        elif [ "${ext}" = ".h" ] ; then
             cp $f $BLD_OUT_DIR/inc
         elif [ "${ext}" = "${SHOBJ}" ] ; then
-            ${BLD_TOOLS_DIR}/getlib $f
+            QUIET=1 ${BLD_TOOLS_DIR}/getlib $f
         elif [ "${ext}" = ".mod" -o "${ext}" = ".a" ] ; then
             cp $f $BLD_OUT_DIR/lib
         else
